apiVersion: apps/v1
kind: Deployment
metadata:
  name: bombardier
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bombardier
  template:
    metadata:
      labels:
        app: bombardier
    spec:
      containers:
      - args:
        - -f
        - /dev/null
        command:
        - tail
        image: alpine/bombardier
        name: bombardier
